#!/usr/bin/ruby

require 'rest_client'

p RestClient.get 'http://localhost:8000/api/prospects'


1000.times {
  budget = JSON.parse(File.read('seeds/data/prospects/budget.json')).sample

  prospect = {
      ref_agence:   JSON.parse(File.read('seeds/data/prospects/agency_title.json')).sample,
      description:  JSON.parse(File.read('seeds/data/prospects/description.json')).sample,
      budget_min:   budget[0].to_i,
      budget_max:   budget[1].to_i,
      bedroomcount: JSON.parse(File.read('seeds/data/common/bedroomcount.json')).sample.to_i,
      surface:      JSON.parse(File.read('seeds/data/common/surface.json')).sample.to_i,
      location: {
          lat: JSON.parse(File.read('seeds/data/prospects/lat.json')).sample,
          lon: JSON.parse(File.read('seeds/data/prospects/lon.json')).sample
      },
      agency_id: JSON.parse(File.read('seeds/data/common/agencyid.json')).sample.to_i,

  }
  p prospect

  RestClient.post( 'http://localhost:8000/api/prospects', prospect)
}

